# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('huiuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RankID', models.IntegerField()),
                ('RankName', models.CharField(max_length=64)),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='datetables',
        ),
    ]
