# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huiuapp', '0003_auto_20160922_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='RankWeb',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
