# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huiuapp', '0005_auto_20161014_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='createdTime',
        ),
        migrations.AddField(
            model_name='status',
            name='idlestat',
            field=models.TextField(default=''),
        ),
    ]
