# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huiuapp', '0006_auto_20161016_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='momeryfree',
            new_name='memoryfree',
        ),
    ]
