# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huiuapp', '0007_auto_20161016_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
