# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huiuapp', '0008_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlestat', models.TextField(default='')),
                ('systime', models.TextField()),
                ('usersnumber', models.TextField()),
                ('loadavg', models.TextField()),
                ('cpufree', models.TextField()),
                ('memoryfree', models.TextField()),
            ],
        ),
    ]
